{{- if .Values.cert.clusterIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: jiangsier-trojan-letsencrypt-http01
  labels:
    {{- include "helm-config.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- if .Values.cert.email }}
    email: {{ .Values.cert.email }}
    {{- end }}
    privateKeySecretRef:
      name: {{ include "helm-config.name" . }}-letsencrypt-http01-key
    solvers:
        - http01:
          ingress:
            class: {{ .Values.ingress.className }}
  {{- end }}