{{- if .Values.deployment.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: trojan-config
data:
  config.json: |
    {
        "run_type": "server",
        "local_addr": "::",
        "local_port": {{ default 443 .Values.service.port }},
        "remote_addr": {{ default "127.0.0.1" .Values.trojan.remote.addr | quote }},
        "remote_port": {{ default 80 .Values.trojan.remote.port }},
        "password": [
            {{ default "" .Values.trojan.password | quote }}
        ],
        "log_level": 1,
        "ssl": {
            "cert": {{ .Values.trojan.ssl.cert | quote }},
            "key": {{ .Values.trojan.ssl.key | quote }},
            "key_password": "",
            "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
            "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
            "prefer_server_cipher": false,
            "reuse_session": true,
            "session_ticket": false,
            "session_timeout": 600,
            "plain_http_response": ""
        },
        "tcp": {
            "prefer_ipv4": false,
            "no_delay": true,
            "keep_alive": true,
            "reuse_port": false,
            "fast_open": false,
            "fast_open_qlen": 20
        }
    }
{{- end }}
